use tonic;

use crate::{
    ReceiverSortBy, ReceiversArgs, SenderSortBy, SendersArgs,
    database::{DATABASE_URL, DatabaseLocation, DatabaseManager},
    email::stats::{get_receiver_stats_rows, get_sender_stats_rows},
    email::types::{ReceiverStats as ReceiverStatsEmail, SenderStats as SenderStatsEmail},
    grpc::grpc_server::{
        ReceiverStats as ReceiverStatsProto, SenderStats as SenderStatsProto,
        stats_server::{Stats, StatsServer},
    },
};

tonic::include_proto!("emailyzer.stats");

/// Encoded `FileDescriptorSet` generated by `build.rs`, used to power gRPC server reflection
/// (e.g. for `grpcurl`/`grpcui`) without requiring clients to ship a copy of the `.proto` file.
const FILE_DESCRIPTOR_SET: &[u8] = tonic::include_file_descriptor_set!("stats_descriptor");

/// Default number of rows returned per page when the client doesn't specify `page_size`.
const DEFAULT_PAGE_SIZE: usize = 50;

struct StatsService {}

/// Shared cursor-pagination helpers so `get_sender_stats`/`get_receiver_stats` stay in sync.
/// Rows must already be sorted by their cursor key (sender/receiver) before calling these.
fn resolve_page_size(requested: u32) -> usize {
    if requested == 0 {
        DEFAULT_PAGE_SIZE
    } else {
        requested as usize
    }
}

/// The cursor is the key of the last row returned in the previous page. Skip everything up to
/// and including it to get the next page. An empty or unknown cursor starts from the beginning.
fn find_start_index(sorted_keys: &[&str], cursor: &str) -> usize {
    if cursor.is_empty() {
        0
    } else {
        sorted_keys
            .iter()
            .position(|key| *key == cursor)
            .map(|index| index + 1)
            .unwrap_or(0)
    }
}

/// There's a next page iff this page was full (reached page_size), meaning there could be more
/// rows after the last one we're returning.
fn next_cursor(page_keys: &[&str], page_size: usize) -> String {
    if page_keys.len() == page_size {
        page_keys
            .last()
            .map(|key| key.to_string())
            .unwrap_or_default()
    } else {
        String::new()
    }
}

#[tonic::async_trait]
impl Stats for StatsService {
    async fn get_sender_stats(
        &self,
        request: tonic::Request<SenderStatsRequest>,
    ) -> std::result::Result<tonic::Response<SenderStatsResponse>, tonic::Status> {
        let request = request.into_inner();
        let page_size = resolve_page_size(request.page_size);

        let db_manager = DatabaseManager::new(DatabaseLocation::File(DATABASE_URL))
            .await
            .map_err(|error| tonic::Status::internal(error.to_string()))?;

        // Sort by sender (the cursor key) so pagination order is stable across requests.
        let mut sender_stats = get_sender_stats_rows(
            SendersArgs {
                refresh: false,
                sender: vec![],
                sort_by: Some(SenderSortBy::Sender),
                top: None,
                provider: None,
            },
            &db_manager,
        )
        .await
        .map_err(|error| tonic::Status::internal(error.to_string()))?;
        sender_stats.sort_by(|a, b| a.sender.cmp(&b.sender));

        let keys: Vec<&str> = sender_stats
            .iter()
            .map(|stat| stat.sender.as_str())
            .collect();
        let start_index = find_start_index(&keys, &request.cursor);

        let page: Vec<SenderStatsEmail> = sender_stats
            .into_iter()
            .skip(start_index)
            .take(page_size)
            .collect();

        let page_keys: Vec<&str> = page.iter().map(|stat| stat.sender.as_str()).collect();
        let next_cursor = next_cursor(&page_keys, page_size);

        let sender_stats_protos: Vec<SenderStatsProto> =
            page.into_iter().map(|stat| stat.into()).collect();

        let response = SenderStatsResponse {
            sender_stats: sender_stats_protos,
            next_cursor,
        };

        Ok(tonic::Response::new(response))
    }

    async fn get_receiver_stats(
        &self,
        request: tonic::Request<ReceiverStatsRequest>,
    ) -> std::result::Result<tonic::Response<ReceiverStatsResponse>, tonic::Status> {
        let request = request.into_inner();
        let page_size = resolve_page_size(request.page_size);

        let db_manager = DatabaseManager::new(DatabaseLocation::File(DATABASE_URL))
            .await
            .map_err(|error| tonic::Status::internal(error.to_string()))?;

        // Sort by receiver (the cursor key) so pagination order is stable across requests.
        let mut receiver_stats = get_receiver_stats_rows(
            ReceiversArgs {
                refresh: false,
                receiver: vec![],
                sort_by: Some(ReceiverSortBy::Receiver),
                top: None,
                provider: None,
            },
            &db_manager,
        )
        .await
        .map_err(|error| tonic::Status::internal(error.to_string()))?;
        receiver_stats.sort_by(|a, b| a.receiver.cmp(&b.receiver));

        let keys: Vec<&str> = receiver_stats
            .iter()
            .map(|stat| stat.receiver.as_str())
            .collect();
        let start_index = find_start_index(&keys, &request.cursor);

        let page: Vec<ReceiverStatsEmail> = receiver_stats
            .into_iter()
            .skip(start_index)
            .take(page_size)
            .collect();

        let page_keys: Vec<&str> = page.iter().map(|stat| stat.receiver.as_str()).collect();
        let next_cursor = next_cursor(&page_keys, page_size);

        let receiver_stats_protos: Vec<ReceiverStatsProto> =
            page.into_iter().map(|stat| stat.into()).collect();

        let response = ReceiverStatsResponse {
            receiver_stats: receiver_stats_protos,
            next_cursor,
        };

        Ok(tonic::Response::new(response))
    }
}

pub async fn launch() -> anyhow::Result<()> {
    let address = "0.0.0.0:8080".parse()?;
    let stats_service = StatsService {};

    let reflection_service = tonic_reflection::server::Builder::configure()
        .register_encoded_file_descriptor_set(FILE_DESCRIPTOR_SET)
        .build_v1()?;

    println!("Starting gRPC server on {}", address);

    tonic::transport::Server::builder()
        .add_service(StatsServer::new(stats_service))
        .add_service(reflection_service)
        .serve(address)
        .await?;
    Ok(())
}

impl From<SenderStatsEmail> for SenderStatsProto {
    fn from(sender_stat: SenderStatsEmail) -> Self {
        Self {
            sender: sender_stat.sender,
            total_emails: sender_stat.total_emails,
            read_emails: sender_stat.read_emails,
            unread_emails: sender_stat.unread_emails,
            attachment_count: sender_stat.attachment_count,
            no_attachment_count: sender_stat.no_attachment_count,
        }
    }
}

impl From<ReceiverStatsEmail> for ReceiverStatsProto {
    fn from(receiver_stat: ReceiverStatsEmail) -> Self {
        Self {
            receiver: receiver_stat.receiver,
            total_emails: receiver_stat.total_emails,
            read_emails: receiver_stat.read_emails,
            unread_emails: receiver_stat.unread_emails,
            attachment_count: receiver_stat.attachment_count,
            no_attachment_count: receiver_stat.no_attachment_count,
        }
    }
}
